name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.11.5
  - chardet=3.0.4
  - conda=4.6.13
  - conda-env=2.6.0
  - cryptography=2.4.2
  - dbus=1.13.2
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - ipykernel=5.1.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.1
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.7
  - openssl=1.1.1b
  - pandoc=2.7.1
  - pandocfilters=1.4.2
  - parso=0.3.4
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=18.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=18.0.0
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - python=3.7.1
  - pyzmq=18.0.1
  - qt=5.6.3
  - qtconsole=4.4.3
  - readline=7.0
  - requests=2.21.0
  - ruamel_yaml=0.15.46
  - send2trash=1.5.0
  - setuptools=40.6.3
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - h5py==2.9.0
    - numpy==1.15.4
    - pandas==0.23.4
    - python-dateutil==2.7.5
    - pytz==2018.7

