name: ds_base_env
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - imbalanced-learn=0.4.3
  - jupyter=1.0.0
  - matplotlib=2.2.3
  - notebook=5.6.0
  - numpy=1.15.2
  - pandas=0.23.4
  - python=3.5.5
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - pip:
    - kaggle==1.5.3
    - lightgbm==2.2.3
    - pip==19.0.3
    - tqdm==4.31.1
    - xgboost==0.82

